### ISSUE TITLE
Add hotkey to quick change AlwaysOnTop status?

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-electron-window-tweaker#1]
Like if I need ob alwaysontop, I could use hotkey to trigger it.

**Comment by mgmeyers** [comment]
This is still to come, but the new version adds a menu to the status bar to adjust the settings.

<img width="240" alt="Screen Shot 2021-06-09 at 3 33 14 PM" src="https://user-images.githubusercontent.com/2694747/121437960-038f3300-c938-11eb-8f26-d79372228a2c.png">

**Comment by Quorafind** [comment]
Nice job
