### ISSUE TITLE
Acrylic Window

### ISSUE THREAD

**Issue by chetachiezikeuzor** [mgmeyers/obsidian-electron-window-tweaker#3]
Hello! Just wondering if it would be possible to get electron acrylic window into Obsidian 👀. Phenomenal plugin btw 🤗
https://www.npmjs.com/package/electron-acrylic-window

![](https://raw.githubusercontent.com/Seo-Rii/electron-acrylic-window/HEAD/screenshots/6.png)

**Comment by mgmeyers** [comment]
@chetachiezikeuzor I believe that obsidian already uses electron-acrylic-window on windows to achieve the translucency effect! On mac, it uses the built in OS translucency.

**Comment by chetachiezikeuzor** [comment]
Oh wow, I didn't know that! Thank you! 😊
