### ISSUE TITLE
[Feature Request] Ability to set custom keyboard shortcuts

### ISSUE THREAD

**Issue by EdualcLaiv** [mgmeyers/obsidian-electron-window-tweaker#4]
Hello,

Do you think it would be possible to add the ability to add custom keyboard shortcuts for oppacity up and down in the settings ?

Anyway, nice plugin :)

**Comment by mgmeyers** [comment]
@EdualcLaiv I've added two commands to increase and decrease opacity. Let me know if you have any issues with them.
